version: '2'
services: 
  mongodb: 
    image: mongo
    container_name: mongodb
    ports: 
      - "27017:27017"

  b_anticafe_core: 
    image: onebytecode/b_anticafe_core
    container_name: b_anticafe_core
    depends_on:
      - mongodb
    links:
     - mongodb
    ports: 
      - "8080:8080"
